apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}
spec:
  template:
    spec:
      containers:
      - name: psql-client
        image: postgres:14.9-alpine
        command:
        - "psql"
        - "{{ .Values.connectdb }}"
        - "-c"
        - "CREATE TABLE IF NOT EXISTS todo (todo_id SERIAL PRIMARY KEY, description VARCHAR(255));"
      restartPolicy: Never