apiVersion: v1
kind: Service
metadata:
  namespace: to-do-app
  name: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: to-do-app
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{  .Values.replicas  }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: mycontainer
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
          - name : PORT
            value : "5000"
          - name: DB_HOST
            value: {{ .Values.env.db_host }}
          - name: DB_PASSWORD
            value: {{ .Values.env.password }}
          readinessProbe:
            httpGet:
              path: /todos
              port: 5000
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "100Mi"
              cpu: "50m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
