name: Webhook Triggered Workflow

on:
  repository_dispatch: # Triggered by an external webhook

jobs:
  webhook_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "This workflow was triggered by a webhook event!"

